### ISSUE TITLE
A question about code environment 

### ISSUE THREAD

**Issue by mikutown** [iDylanCui/ARN#2]
Could you plz tell me the environment version list of this code? you can get them by input ‘pip list’ in terminal.

**Comment by gongchuanyang** [comment]
在吗？能不能讨论一下

**Comment by mikutown** [comment]
> 

python3.8，torch1.21.0 cuda11.3

**Comment by gongchuanyang** [comment]
你能获得他文件中的权重文件吗？

**Comment by mikutown** [comment]
目前不能哦qwq
